#!/usr/bin/env node
// AI-Ops Navigator — zero-dependency local server for browsing, editing, and
// mapping an AI-Ops engagement workspace. Localhost only, no auth.
//
//   node server.mjs                      # serves the current working directory
//   ROOT=/path/to/engagement node server.mjs --port 4173
//
// Point ROOT at the folder the AI-Ops Consultant writes into (profile/roles/
// tools/workflows + an .ai-ops/ state folder).
import { createServer } from 'node:http';
import { readFile, writeFile, readdir, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// --- config ----------------------------------------------------------------
const argPort = (() => {
  const i = process.argv.indexOf('--port');
  if (i === -1) return null;
  const v = process.argv[i + 1];
  const n = Number(v);
  if (v === undefined || v.trim() === '' || !Number.isInteger(n) || n < 1 || n > 65535) {
    console.error(`error: --port expects a number between 1 and 65535 (got ${v === undefined ? 'nothing' : JSON.stringify(v)})`);
    process.exit(1);
  }
  return n;
})();
const PORT = argPort || Number(process.env.PORT) || 4173;
// Workspace root = the engagement folder this navigator documents.
// Defaults to the current working directory; override with ROOT=...
const ROOT = path.resolve(process.env.ROOT || process.cwd());
const PUBLIC = path.join(__dirname, 'public');

const slugify = (s) => s.toLowerCase().trim().replace(/['"]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const today = () => new Date().toISOString().slice(0, 10);

// Built-in stub templates per category. {{today}} is filled on create.
// roles / tools / workflows mirror the abbreviated stub shapes inlined in
// skills/ai-ops/prompts/library-assembly.md (themselves derived from
// skills/ai-ops/templates/) so all stub sources agree.
const STUB_MARKER = '<!-- Stub generated by navigator on {{today}}. Enrich in a dedicated session. -->\n\n';
const TEMPLATES = {
  roles: (t) => `${STUB_MARKER}# ${t}

**Department:** <department or team this role belongs to>
**Reports to:** <role title>
**Last updated:** {{today}}

The goal of this role is to <one sentence: what outcome this role exists to produce>.

This person is a <one sentence: archetype>.

## Objectives + Metrics

- **<Objective>** — <what success looks like> · Metric: <how it's measured>

## Role Responsibilities

### Core Loop

#### <Cadence>

- [ ] **<Action verb>** — <what + why> using [<tool>](../tools/<tool-slug>.md)

### Triggered Tasks

- [ ] **<Action verb>** — when <trigger> → <what + why>

### Infinite Tasks

- [ ] **<Action verb>** — <ongoing responsibility>

## KOODAR Breakdown

### K — Know
### O — Observe
### O — Orient
### D — Decide
### A — Act
### R — Review
`,
  tools: (t) => `${STUB_MARKER}# ${t}

**Website:** <url>
**API docs:** <url or "none">
**Plan / tier:** <what the user is currently paying for>
**Cloud or local:** <cloud SaaS | on-prem | desktop app | self-hosted>
**Last updated:** {{today}}

## Purpose

<1–2 sentences. What this tool does for the business and why it exists in the stack.>

## Records in this tool

- **<record-slug>** — <one-line description; inline notes on format / access when known>
- **<record-slug>** (Synced from <tool-slug>) — <description>
- **<record-slug>** (Exported to <tool-slug>) — <description>
- **<record-slug>** (Bidirectional sync with <tool-slug>) — <description>

A record without a flow tag is owned by this tool. For the full cross-tool registry and fragmentation analysis, see [data-architecture.md](../data-architecture.md).

## Integrations

- **<Automation platform>** — <what's connected and how>
- **<Native integration>** — <what it connects to natively>
- **<MCP / plugin>** — <if relevant>
`,
  workflows: (t) => `${STUB_MARKER}# ${t}

**Owner role:** → [<role-slug>.md](../roles/<role-slug>.md)
**Last updated:** {{today}}

## Jobs-to-be-done

When <trigger>, <role> wants to <motivation>, so <outcome>.

## SOP

<!-- Step format (powers the Workflow Map), one step per "- [ ]" line: -->
<!--   - [ ] **<Action verb>** — <role> uses [tool-slug](../tools/tool-slug.md) on <record> — <produces what> -->
<!-- Sub-bullets "- Exception: <what> → <how it's handled>" and "- Escalate: <when> → <who>" attach to the step above them. -->

- [ ] **<Action verb>** — <role> uses <tool> on <data> — <produces what>

### Flowchart — ASCII (for humans)

< plain-text box-and-arrow diagram >

### Flowchart — Mermaid (for machines)

< mermaid code >

## Automation / Agent Potential

**Target KOODAR level:** <K | KA | KDA | KDAR | KODAR | KOODAR>
**Lives in:** <which of the user's AI tools>
**Approach:** <Use existing integration | Install / configure a skill | Custom workflow | Other>

<Narrative.>

**Constraints:**
- Prior attempts / prior approach: <what was tried, what broke, why>
- Integration walls: <locked APIs, on-prem tools, vendor limits>
`,
  decisions: (t) => `${STUB_MARKER}# ${t}

**Status:** proposed
**Date:** {{today}}

## Decision

<what was decided>

## What forced it

<context / constraint that drove this>
`,
  scopes: (t) => `${STUB_MARKER}# ${t}

**Status:** draft
**Last updated:** {{today}}

## Outcome

<the result this build delivers>

## Scope

-

## Out of scope

-
`,
  roadmaps: (t) => `${STUB_MARKER}# ${t}

**Scope:** <company | department | role | workflow>
**Last updated:** {{today}}

## Sequence

1.

## Projected friction reduction

-
`,
  glossary: (t) => `${STUB_MARKER}# ${t}

<term> — <one-sentence definition as this client uses it>.
`,
};
const CATEGORY_DIR = { roles: 'roles', tools: 'tools', workflows: 'workflows', decisions: 'decisions', scopes: 'scopes', roadmaps: 'roadmaps' };

// Categories we surface as graph node groups (folder -> label).
const CATEGORIES = {
  '.': 'profile',
  roles: 'roles',
  tools: 'tools',
  workflows: 'workflows',
  scopes: 'scopes',
  roadmaps: 'roadmaps',
  decisions: 'decisions',
  meetings: 'meetings',
  '.ai-ops': 'ops',
};

// --- helpers ---------------------------------------------------------------
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
};

function send(res, code, body, type = 'application/json; charset=utf-8') {
  res.writeHead(code, { 'Content-Type': type, 'Cache-Control': 'no-store' });
  res.end(typeof body === 'string' || Buffer.isBuffer(body) ? body : JSON.stringify(body));
}

// Resolve a workspace-relative path safely (no escaping ROOT, .md only for writes).
function safeResolve(rel) {
  const abs = path.resolve(ROOT, rel || '.');
  if (abs !== ROOT && !abs.startsWith(ROOT + path.sep)) return null;
  return abs;
}

// Is this absolute path inside the consultant's .ai-ops/ control folder?
function isUnderAiOps(abs) {
  const aiOps = path.join(ROOT, '.ai-ops').toLowerCase();
  const low = abs.toLowerCase();
  return low === aiOps || low.startsWith(aiOps + path.sep);
}

async function walk(dir, base = '') {
  const out = [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    if (e.name.startsWith('.git') || e.name === 'node_modules') continue;
    const full = path.join(dir, e.name);
    const rel = base ? `${base}/${e.name}` : e.name;
    if (e.isDirectory()) {
      // Don't serve the navigator's own app directory when ROOT contains it;
      // a client library's unrelated "navigator" folder stays visible.
      if (path.resolve(full) === __dirname) continue;
      out.push(...(await walk(full, rel)));
    } else if (e.name.endsWith('.md')) {
      out.push(rel);
    }
  }
  return out;
}

function categoryOf(rel) {
  const dir = path.posix.dirname(rel.split(path.sep).join('/'));
  const top = dir === '.' ? '.' : dir.split('/')[0];
  return CATEGORIES[top] || top || 'other';
}

function titleFromContent(content, rel) {
  const m = content.match(/^#\s+(.+)$/m);
  if (m) return m[1].trim();
  return path.basename(rel, '.md');
}

// Parse markdown links to other .md files in the workspace -> graph edges.
function extractLinks(content, fromRel) {
  const fromDir = path.posix.dirname(fromRel.split(path.sep).join('/'));
  const edges = new Set();
  const re = /\]\(([^)]+\.md)(?:#[^)]*)?\)/g;
  let m;
  while ((m = re.exec(content))) {
    let target = m[1].trim();
    if (/^https?:/i.test(target)) continue;
    target = decodeURIComponent(target);
    const resolved = path.posix.normalize(path.posix.join(fromDir, target));
    edges.add(resolved.replace(/^\.\//, ''));
  }
  return [...edges];
}

// Resolve a relative .md link found in `content` to a workspace-relative id.
function resolveLink(content, fromRel, regex) {
  const fromDir = path.posix.dirname(fromRel.split(path.sep).join('/'));
  const m = content.match(regex);
  if (!m) return null;
  const t = path.posix.normalize(path.posix.join(fromDir, decodeURIComponent(m[1])));
  return t.replace(/^\.\//, '');
}

// Parse the SOP section into a tree of role/tool-tagged steps.
//
// Canonical step format (skills/ai-ops/templates/workflow.md + workflow-sop prompt):
//   - [ ] **<Action verb>** — <role> uses <tool> on <record> — <produces what>
//     - Exception: <what can go wrong> → <how it's handled>
//     - Escalate: <condition> → <who/where>
// <role> and <tool> may be plain names or markdown links like
// [tool-slug](../tools/tool-slug.md). Exception / Escalate sub-bullets attach
// to the step above them as exception paths.
//
// The legacy backtick format still parses (backward compatibility):
//   - [ ] **Action** — `Role` uses `Tool` — note
//     - [ ] **(if yes)** **Action** — `Role` uses `Tool` — ⚠ note
function parseSteps(content) {
  const sec = content.match(/##\s*SOP\s*\n([\s\S]*?)(\n##\s|$)/);
  if (!sec) return [];
  const stripLinks = (s) => s.replace(/\[([^\]]*)\]\([^)]*\)/g, '$1');
  const isPlaceholder = (s) => /^<[^<>]*>$/.test(s) || /^(…|\.\.\.)$/.test(s);
  const roots = [];
  const stack = [{ level: -1, children: roots, step: null }];
  for (const raw of sec[1].split('\n')) {
    const m = raw.match(/^(\s*)[-*]\s+(.*)$/);
    if (!m) continue;
    const indent = m[1].replace(/\t/g, '  ').length;
    const hadCheckbox = /^\[[ xX]\]\s*/.test(m[2]);
    let text = m[2].replace(/^\[[ xX]\]\s*/, '').trim();
    while (stack.length > 1 && indent <= stack[stack.length - 1].level) stack.pop();
    const parent = stack[stack.length - 1];

    // "- Exception: ..." / "- Escalate: ..." sub-bullets attach to the parent step.
    const exm = text.match(/^\*{0,2}(Exception|Escalate)\*{0,2}\s*:\s*(.*)$/i);
    if (exm && !hadCheckbox) {
      if (parent.step) {
        const kind = exm[1][0].toUpperCase() + exm[1].slice(1).toLowerCase();
        parent.step.exceptions.push({ kind, text: stripLinks(exm[2]).trim() });
      }
      continue;
    }

    let step;
    const codes = [...text.matchAll(/`([^`]+)`/g)].map((c) => c[1].trim());
    if (codes.length > 0) {
      // Legacy backtick format.
      const exception = /⚠|\(exception\)|\[exception\]/i.test(text);
      text = text.replace(/⚠|\(exception\)|\[exception\]/gi, '').trim();
      const bolds = [...text.matchAll(/\*\*(.+?)\*\*/g)].map((b) => b[1].trim());
      let branch = null, action;
      if (bolds[0] && /^[([].*[)\]]$/.test(bolds[0])) { branch = bolds[0].replace(/^[([]|[)\]]$/g, '').trim(); action = bolds[1] || ''; }
      else { action = bolds[0] || text.replace(/`[^`]*`/g, '').replace(/[—–-].*$/, '').trim(); }
      if (!branch) { const pm = text.match(/^\(([^)]+)\)/); if (pm) branch = pm[1].trim(); }
      const lastTick = text.lastIndexOf('`');
      const note = text.slice(lastTick + 1).replace(/^[\s—–-]*(uses|on)?\s*/i, '').replace(/^[\s—–-]+/, '').trim();
      step = { action, role: codes[0] || null, tool: codes[1] || null, record: null, note, branch, exception, exceptions: [], children: [] };
    } else if (hadCheckbox) {
      // Canonical template format: action — <role> uses <tool> on <record> — note.
      const parts = stripLinks(text).split(/\s+[—–]\s+/).map((s) => s.trim()).filter(Boolean);
      const action = (parts[0] || '').replace(/\*\*/g, '').trim();
      let role = null, tool = null, record = null, note = parts.slice(2).join(' — ').trim();
      if (parts[1]) {
        const um = parts[1].match(/^(.+?)\s+uses\s+(.+)$/i);
        if (um) {
          role = um[1].trim() || null;
          const rest = um[2].trim();
          const om = rest.match(/^(.+?)\s+on\s+(.+)$/i);
          if (om) { tool = om[1].trim() || null; record = om[2].trim() || null; }
          else tool = rest || null;
        } else {
          // Middle clause without "uses" — keep it readable as part of the note.
          note = [parts[1], note].filter(Boolean).join(' — ');
        }
      }
      step = { action, role, tool, record, note, branch: null, exception: false, exceptions: [], children: [] };
    } else {
      continue; // prose bullet — not a step
    }
    if (isPlaceholder(step.action)) continue; // unfilled template line
    parent.children.push(step);
    stack.push({ level: indent, children: step.children, step });
  }
  return roots;
}

function parseField(content, label) {
  const escaped = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const m = content.match(new RegExp('\\*\\*' + escaped + ':\\*\\*[ \\t]*(.*)$', 'm'));
  if (!m) return null;
  const raw = m[1].trim();
  if (!raw || raw.startsWith('<')) return null; // empty or unfilled template placeholder
  const v = raw.replace(/[→\[\]]/g, '').trim().split('(')[0].trim();
  return v || null;
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', (c) => (data += c));
    req.on('end', () => resolve(data));
    req.on('error', reject);
  });
}

// --- graph builder ----------------------------------------------------------
async function buildGraph() {
  const files = await walk(ROOT);
  const nodes = [];
  const edges = [];
  const known = new Set(files.map((f) => f.split(path.sep).join('/')));
  for (const relRaw of files) {
    const rel = relRaw.split(path.sep).join('/');
    const content = await readFile(path.join(ROOT, relRaw), 'utf8').catch(() => '');
    // Marker covers both library-assembly and navigator stubs; tiny files count too.
    const isStub = /Stub generated by/i.test(content) || content.trim().length < 200;
    const cat = categoryOf(relRaw);
    const node = {
      id: rel,
      label: titleFromContent(content, rel),
      category: cat,
      stub: isStub,
    };
    if (cat === 'roles') {
      node.department = parseField(content, 'Department');
      node.reportsToName = parseField(content, 'Reports to');
    }
    if (cat === 'workflows') {
      node.ownerRole = resolveLink(content, rel, /Owner role:\*\*\s*(?:→\s*)?\[[^\]]*\]\(([^)]+\.md)\)/);
      node.steps = parseSteps(content);
    }
    nodes.push(node);
    for (const t of extractLinks(content, rel)) {
      if (known.has(t) && t !== rel) edges.push({ from: rel, to: t });
    }
  }
  // resolve role "Reports to" names -> role node ids (by label, case-insensitive)
  const roleByLabel = {};
  nodes.filter((n) => n.category === 'roles').forEach((n) => (roleByLabel[n.label.toLowerCase()] = n.id));
  for (const n of nodes) {
    if (n.category !== 'roles' || !n.reportsToName) continue;
    n.reportsToId = roleByLabel[n.reportsToName.toLowerCase()] || null; // null = top-level (e.g. "Self")
  }
  return { root: path.basename(ROOT), nodes, edges };
}

// --- routes -----------------------------------------------------------------
const ALLOWED_HOST = /^(localhost|127\.0\.0\.1)(:\d+)?$/i;
const allowedOrigins = () => [`http://localhost:${PORT}`, `http://127.0.0.1:${PORT}`];

const server = createServer(async (req, res) => {
  // Reject DNS-rebinding / cross-site requests: Host must be localhost.
  const host = req.headers.host || '';
  if (!ALLOWED_HOST.test(host)) return send(res, 403, { error: 'forbidden: bad Host header' });
  // Browser-originated cross-origin writes carry an Origin header — reject them.
  if (req.method === 'POST') {
    const origin = req.headers.origin;
    if (origin && !allowedOrigins().includes(origin.toLowerCase())) {
      return send(res, 403, { error: 'forbidden: cross-origin request rejected' });
    }
  }
  const url = new URL(req.url, `http://localhost:${PORT}`);
  const p = url.pathname;
  try {
    if (p === '/api/graph') return send(res, 200, await buildGraph());

    if (p === '/api/file' && req.method === 'GET') {
      const rel = url.searchParams.get('path') || '';
      const abs = safeResolve(rel);
      if (!abs || !existsSync(abs)) return send(res, 404, { error: 'not found' });
      const content = await readFile(abs, 'utf8');
      return send(res, 200, { path: rel, content });
    }

    if (p === '/api/file' && req.method === 'POST') {
      const { path: rel, content } = JSON.parse(await readBody(req));
      const abs = safeResolve(rel);
      if (!abs || !abs.toLowerCase().endsWith('.md')) return send(res, 400, { error: 'only .md writes allowed' });
      if (isUnderAiOps(abs)) return send(res, 403, { error: '.ai-ops/ is read-only here (consultant control files)' });
      await mkdir(path.dirname(abs), { recursive: true });
      await writeFile(abs, content, 'utf8');
      return send(res, 200, { ok: true, path: rel });
    }

    if (p === '/api/new' && req.method === 'POST') {
      const { category, title } = JSON.parse(await readBody(req));
      const dir = CATEGORY_DIR[category];
      const tpl = TEMPLATES[category];
      if (!dir || !tpl) return send(res, 400, { error: 'unknown category' });
      const slug = slugify(title || '');
      if (!slug) return send(res, 400, { error: 'title required' });
      const rel = `${dir}/${slug}.md`;
      const abs = safeResolve(rel);
      if (!abs) return send(res, 400, { error: 'bad path' });
      if (existsSync(abs)) return send(res, 409, { error: 'a page with that name already exists', path: rel });
      await mkdir(path.dirname(abs), { recursive: true });
      await writeFile(abs, tpl(title).replace(/\{\{today\}\}/g, today()), 'utf8');
      return send(res, 200, { ok: true, path: rel });
    }

    // static files
    let file = p === '/' ? '/index.html' : p;
    const abs = path.join(PUBLIC, file);
    if (!abs.startsWith(PUBLIC) || !existsSync(abs)) return send(res, 404, 'Not found', 'text/plain');
    const ext = path.extname(abs);
    return send(res, 200, await readFile(abs), MIME[ext] || 'application/octet-stream');
  } catch (err) {
    return send(res, 500, { error: String(err && err.message || err) });
  }
});

server.on('error', (err) => {
  if (err && err.code === 'EADDRINUSE') {
    console.error(`error: port ${PORT} is already in use — stop the other process or pick another port with --port <n>`);
  } else {
    console.error(`error: ${err && err.message || err}`);
  }
  process.exit(1);
});

server.listen(PORT, '127.0.0.1', () => {
  console.log(`\n  AI-Ops Navigator`);
  console.log(`  workspace : ${ROOT}`);
  console.log(`  open      : http://localhost:${PORT}\n`);
});
